### ISSUE TITLE
Launcher Icon

### ISSUE THREAD

**Issue by estheryjeon** [loafyyy/egyptian-rat-screw-android#2]
![logo-01](https://user-images.githubusercontent.com/32020849/34450421-b792f698-eccd-11e7-95b0-2d55300db2e0.png)

**Comment by loafyyy** [comment]
Can we add an image to this?

**Comment by estheryjeon** [comment]
was thinking something like this? gonna try a version with cards too
![logo-01](https://user-images.githubusercontent.com/32020849/34464692-0e62a17e-ee51-11e7-9001-cc22c0253eef.png)
